[tool.poetry]
name = "fsvreader"
version = "0.1.0"
description = ""
authors = ["Språkbanken Text <sb-info@svenska.gu.se>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
Flask = "^2.0.2"
gunicorn = "^20.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
